version: '3.8'

services:
  redis: 
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    ports: 
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RATE_LIMIT_IP=10
      - RATE_LIMIT_TOKEN=100
      - RATE_LIMIT_DURATION_SECONDS=300
    depends_on:
      - redis

volumes:
  redis_data:
